# Generated by Django 3.0.5 on 2020-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksm_app', '0003_auto_20200503_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatantsbattle',
            name='transmisja',
            field=models.URLField(blank=True),
        ),
    ]
