# Generated by Django 3.0.5 on 2020-05-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksm_app', '0004_auto_20200503_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatants',
            name='zdjęcie',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='judges',
            name='zdjęcie',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
