# Generated by Django 3.0.5 on 2020-05-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksm_app', '0005_auto_20200504_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debatants',
            old_name='zdjęcie',
            new_name='zdjecie',
        ),
        migrations.RenameField(
            model_name='judges',
            old_name='zdjęcie',
            new_name='zdjecie',
        ),
    ]
