# Generated by Django 3.0.5 on 2020-05-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksm_app', '0006_auto_20200504_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordJudges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasło', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='debatants',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='judges',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
