# Generated by Django 3.0.5 on 2020-05-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksm_app', '0007_auto_20200506_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordjudges',
            old_name='hasło',
            new_name='haslo',
        ),
    ]
