# Generated by Django 3.0.5 on 2020-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksm_app', '0011_auto_20200510_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatants',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='judges',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
    ]
