# Generated by Django 3.0.5 on 2020-05-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksm_app', '0012_auto_20200510_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debatants',
            name='zdjecie',
        ),
        migrations.RemoveField(
            model_name='judges',
            name='zdjecie',
        ),
    ]
