# Generated by Django 3.0.5 on 2020-05-14 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksm_app', '0017_auto_20200514_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatantsbattle',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ksm_app.Judges'),
        ),
    ]
