# Generated by Django 3.0.5 on 2020-05-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksm_app', '0020_auto_20200514_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatants',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debatants',
            name='accept2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judges',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judges',
            name='accept2',
            field=models.BooleanField(default=False),
        ),
    ]
